// <auto-generated />
using IslamReasearchBot.DataModules;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IslamReasearchBot.Migrations
{
    [DbContext(typeof(Database))]
    [Migration("20230529172812_mig1")]
    partial class mig1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("IslamReasearchBot.DataModules.ServersData", b =>
                {
                    b.Property<ulong>("ServerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Admins")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RoomsIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("count")
                        .HasColumnType("INTEGER");

                    b.HasKey("ServerID");

                    b.ToTable("ServersData");
                });
#pragma warning restore 612, 618
        }
    }
}
